image: "registry.michelada.io/michelada/dockerfiles/ci/rails:3.0.2"

services:
  - postgres

stages:
  - test
  - deployment

cache:
  paths:
    - vendor/ruby

variables:
  RAILS_ENV: 'test'
  DB_HOST: postgres
  POSTGRES_PASSWORD: loquesea
  POSTGRES_USER: loquesea

before_script:
  - bundle config set clean 'true'
  - bundle config set path 'vendor'
  - bundle install

rubocop:
  stage: test
  script: 
    - yarn install
    - bundle exec rubocop

test:
  stage: test
  script:
    - yarn install
    - bundle exec rake db:create db:schema:load
    - bundle exec rake test

deployment_production:
  stage: deployment
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_PROD --api_key=$HEROKU_API_KEY
  only:
    refs:
      - master

deployment_development:
  stage: deployment
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_STAGING --api_key=$HEROKU_API_KEY
  only:
    refs:
      - development